### ISSUE TITLE
Hard to use in a big project out of the box

### ISSUE THREAD

**Issue by smecsia** [reportportal/agent-java-junit#1]
Hi guys. I decided to try this promising project and to feed my local ReportPortal instance with the test results from JUnit tests. And I faced with the following problems:
* It is not available from the Maven Central, so everybody has to add the custom repository to the config, which is not obvious.
* It has a lot of dependencies (why there are so many?). And the worst thing is that it is using such libraries as Guava and Guice, that are known to be extremely incompatible from version to version. So it becomes almost impossible to solve the appearing depndency hell issues in the big proect with tons of dependencies...

**Comment by avarabyeu** [comment]
hi Ilya. Valid points. Let me comment on them:
1. Deps from bintray will be replicated to Maven Central soon. Actually, i do not think absence in maven central is major issue, but we understand that it's just 'must have'  :)
2. Historically, we started implementation with Google libraries. Don't really think Guice is so backward-incompatible, but absolutely agree that Guava constantly changing API. Moreover, new version of client is coming and it will have rxjava as dependency. Personally, i don't really like idea to rewrite existing stuff to get rid of guice or guava. 
But i understand that users possibly may face 'dependency hell' issues.
To avoid that, we will continue using repackaging technique and hide all stuff related to apache http client and guava.

In general, i agree with need to rewrite client using on vanilla jdk only, but unfortunately we don't have resources to do that in short term. 

Could you please let me know which problems do you have with guice? What classes/packages/logic are not backward-compatible with older versions?

Thanks a lot for interest and valuable comment!

**Comment by smecsia** [comment]
@avarabyeu thank you for your answers and quick response! 
Actually I did not have much time to investigate the incompatibilities. But when I tried to upgrade Guava version, I ended up with some Guice NPE and just gave up, because our dependency tree already looks like a hell :) 
It would be nice to have an easy-to-plug-in solution. So Maven Central mirroring and avoiding the popular libraries, such as Guava in the dependencies would help. 
Anyway, it's great to see this framework in open source. Nice start, keep moving forward.

**Comment by avarabyeu** [comment]
@smecsia That's very useful! Thank you!

**Comment by avarabyeu** [comment]
So, finally, we embedded guava and left guice as transitive dependency. The fun here is that guice is also depends on guava. So, the best option is to embed both of them. But again, not sure if we really need it. If several people raise the same issue again, we will embed them.

**Comment by smecsia** [comment]
@avarabyeu Thank you very much, will try to use newer version and let you know my experience! :+1:

**Comment by dagansandler** [comment]
One year later, but still no Maven Central artifacts... :(

**Comment by qakart** [comment]
me looking for maven central one
