### ISSUE TITLE
Test run is not finished

### ISSUE THREAD

**Issue by kristiansvensson** [reportportal/agent-java-junit#10]
version 2.7.2
Sorry that the code snippets here are in Kotlin, should hopefully be easy to understand anyway.
I'm using ReportPortalListener as follows:

```
fun main(args: Array<String>) {
    val core = JUnitCore()
    core.addListener(ReportPortalListener())
    core.run(BasicLogin::class.java)
}
```

Test class is as follows:
```
class BasicLogin {
    @Test
    fun login_givenWrongCredentials_loginPageIsShown() {
        assertTrue(true)
    }

    @Test
    fun login_givenCorrectCredentials_mainMenuIsShown() {
        assertTrue(false)
    }
}
```

When I run this the test run in ReportPortal is added as expected, but it is never finished.

I have debugged a bit and can see that testFinished() method in ReportPortalListener has a check for # character in method name which fails. Seems to be addressed by [this PR](https://github.com/reportportal/agent-java-junit/pull/6) that has not been merged.

**Comment by DzmitryHumianiuk** [comment]
@kristiansvensson #6 not completed. that's why it's still not merged.

but we also have new version, reimplemented from scratch by contributor.
Plz try `v4` branch. and let us know

**Comment by kristiansvensson** [comment]
I made workaround by extending com.epam.reportportal.junit.ReportPortalListener and making calls to IListenerHandler from there. So at the moment I'm fine. I can wait for a new release.

**Comment by DzmitryHumianiuk** [comment]
@kristiansvensson then closing this issue.
we do some beta testing for new version of jUnit4 agent, but it's slow.

if you would like to participate and speed it up, plz contact me in [Slack chat](https://reportportal-slack-auto.herokuapp.com/)
