### ISSUE TITLE
Not able to see the report

### ISSUE THREAD

**Issue by iaha** [reportportal/agent-java-junit#100]
Hello, I'm trying to connect my project to report portal, but I'm having troubles to see anything on the report portal page.
Let me start saying that my project is a multi module maven project, so I have a pom parent and pom child, all the pom config you describe on the readme I did try it on the POM parent and on the child with not luck, the resources files could only be inside the child project, just because the parent project does not have the structure for it, other detail is that I am using IntelliJ for IDE.
Could you please help me to config this multi module project.
Structure:
![Screen Shot 2021-12-16 at 11 48 15 AM](https://user-images.githubusercontent.com/20776736/146418395-7f4f693b-f27e-4071-a3fa-f8c378d44103.png)

**Comment by HardNorth** [comment]
There is no any details how you configured the agent. Please follow our guideline on the main agent page to configure the agent properly: https://github.com/reportportal/agent-java-junit
