### ISSUE TITLE
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

### ISSUE THREAD

**Issue by kapcool** [reportportal/agent-java-junit#102]
While adding below plugin
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.0</version>
          <configuration>
            
            <argLine>-javaagent:${com.nordstrom.tools:junit-foundation:jar}</argLine>
          </configuration>
        </plugin>

i am getting  this error. 
Error occurred in starting fork, check output in log
Process Exit Code: 1

under surefire reports, below log is coming in file
Error opening zip file or JAR manifest missing : ${com.nordstrom.tools:junit-foundation:jar}

Please help here or help me with the steps to resolve this.

**Comment by HardNorth** [comment]
@kapcool Most likely you missed "maven-dependency-plugin" which does `${com.nordstrom.tools:junit-foundation:jar}` property resolve, see:
https://github.com/reportportal/agent-java-junit#step-52---make-report-portal-agent-invoked-by-the-tests

Please also use our examples here: https://github.com/reportportal/examples-java/tree/master/example-junit
I recently checked it, it works just with `mvn test`.
