### ISSUE TITLE
Possible to use ReportPortalListener with gradle?

### ISSUE THREAD

**Issue by ndinoia** [reportportal/agent-java-junit#16]
In your README.md you have this maven pom setup:

```
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>2.15</version>
   <configuration>
      <properties>
         <property>
            <name>listener</name>
            <value>com.epam.reportportal.junit.ReportPortalListener</value>
         </property>
      </properties>
   </configuration>
</plugin>
```

Is it possible to do this with gradle?

Thanks

**Comment by DzmitryHumianiuk** [comment]
@ndinoia yes, for sure.

@akoltochihin could you plz share example?

**Comment by sbabcoc** [comment]
The new implementation of `agent-java-junit` based on JUnit Foundation makes this super easy. This new agent currently lives in the `v4` branch, but I'm understanding this will be merged into `master` any day now. Find the details of hooking up JUnit run listeners via JUnit Foundation here: 
https://github.com/Nordstrom/JUnit-Foundation/blob/master/README.md#support-for-standard-junit-runlistener-providers

**Comment by ndinoia** [comment]
> The new implementation of `agent-java-junit` based on JUnit Foundation makes this super easy. This new agent currently lives in the `v4` branch, but I'm understanding this will be merged into `master` any day now. Find the details of hooking up JUnit run listeners via JUnit Foundation here:
> https://github.com/Nordstrom/JUnit-Foundation/blob/master/README.md#support-for-standard-junit-runlistener-providers

Thanks @sbabcoc! We've decided to hold off adopting ReportPortal for now due to conflicts with our custom jUnit parameterized runners but I'll make a note to take a look at this down the road.

**Comment by sbabcoc** [comment]
You're in luck! The new JUnit agent will work with your parameterized runner, because it hooks in via a Java agent instead of requiring a custom runner. Give it a try to see how it works for you.

**Comment by sbabcoc** [comment]
BTW - I never provided a link to the `v4` agent: https://github.com/reportportal/agent-java-junit/tree/v4

**Comment by sbabcoc** [comment]
@nicodn Another bonus for your parameterized tests! You can record the test parameters with your results by implementing the [ArtifactParams](https://github.com/Nordstrom/JUnit-Foundation/blob/master/src/main/java/com/nordstrom/automation/junit/ArtifactParams.java) interface. Take a look at [ParameterizedTest](https://github.com/reportportal/agent-java-junit/blob/master/src/test/java/com/epam/reportportal/junit/junit/ParameterizedTest.java) for an example of how this works.
