### ISSUE TITLE
Display logs for @BeforeAll

### ISSUE THREAD

**Issue by sergeidyga-epam** [reportportal/agent-java-junit#27]
No logs (we use log4j2 + JUnit5) related to @BeforeAll method or initialisation are available in ReportPortal UI.

If failure occurred in @BeforeAll (or earlier) - there is no chance to figure it out when evaluating Launches in ReportPortal UI

**Comment by sbabcoc** [comment]
@sergeidyga-epam This agent is specifically for JUnit 4, which doesn't define a @BeforeAll annotation. How this scenario handled by https://github.com/reportportal/agent-java-junit5

**Comment by DzmitryHumianiuk** [comment]
@sergeidyga-epam can you switch to junit5?

**Comment by DzmitryHumianiuk** [comment]
@sbabcoc 
>On this topic. we should probably add the java tag to the agent-java-junit5 project.

or rename this into `agent-java-junit4`
or place both junit5 and juni4 in one repo, but separate folders

**Comment by DzmitryHumianiuk** [comment]
**Resolution:**

closed, since related to jUnit5
