### ISSUE TITLE
Logs in RP UI are not displayed when using @Before annotations in the test

### ISSUE THREAD

**Issue by oleksandr-py** [reportportal/agent-java-junit#51]
Hi guys,

I faced with an issue that no logs or assertion are available in ReportPortl UI if test class contains @Before or @After annotation. Test launch and passed and failed test are displayed, but they are empty. With @BeforeClass and @AfterClass logs and assertions are displayed ReportPortal UI. 
It is possible to reproduce using DummyTest of this project by adding some failed assertions and logs in test methods.

**Comment by MarynaLi** [comment]
+1 I have the same issue

**Comment by HardNorth** [comment]
I believe we fixed this in the latest JUnit 4 agents. E.g. use: agent-java-junit:5.0.0-BETA-9.
Feel free to reopen if the issue is not fixed.
