### ISSUE TITLE
Junit 4 Agent documentation / README.md file should be updated

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/agent-java-junit#57]
I have been digging around attempting to identify what the dependencies are supposed to be in order to use or attempt to use and test the updated agents for use in our environment.

I am assuming that I will only need the compile dependencies in the v5-beta branch and assuming that the transitive dependencies will be resolved without impact on existing projects.

The scope of the dependencies within the documentation should always be set to 'testCompile' or 'testImplementation' in order to exclude the EPAM and dependencies, logback.xml and properties files from being packaged with the resulting package utilizing the reportportal tooling.  logback and properties files should be stored within the src/test/resources directory instead of src/main/resources.

**Comment by evjlobanova** [comment]
@sspieker-cc hello, thank you for posting this, we will go throug all libraries and check dependences and update them.

**Comment by HardNorth** [comment]
OK, I made a script to update README.md automatically, so I believe the issue is resolved.
