### ISSUE TITLE
Retried tests don't reflect properly on RP

### ISSUE THREAD

**Issue by usikraman** [reportportal/agent-java-junit#62]
Tried 3 different ways to retry tests:

1.  surefire plugin option - surefire.rerunFailingTestsCount=1
2. custom test rule
3. junit foundation JUnitRetryAnalyzer

all works, but I'm not able to see retries on RP.

**Comment by HardNorth** [comment]
Fixed in: https://github.com/reportportal/agent-java-junit/pull/75/commits/d6004a5e240afbc57909fa8f0b06f1b4b36b95ac
Please use JUnit Foundation retry feature: https://github.com/sbabcoc/JUnit-Foundation#automatic-retry-of-failed-tests
