### ISSUE TITLE
RP doesn't handle ExpectedException Rule

### ISSUE THREAD

**Issue by usikraman** [reportportal/agent-java-junit#64]
```
    @Rule
    public ExpectedException thrown = ExpectedException.none();

    @Test 
    public void validateVersionNull() {
        thrown.expect(IllegalArgumentException.class);
        thrown.expectMessage("Version cannot be null");
        MessageVersion.validate(null, VERSION2, VERSION3);
    }
```

<img width="860" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/60660404/74105940-c2aac280-4b27-11ea-9842-6938cb032d7d.png">
<img width="522" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/60660404/74105957-eb32bc80-4b27-11ea-8f0c-e5b8cf7aa320.png">

**Comment by HardNorth** [comment]
Fixed in [5.0.0-BETA-16](https://github.com/reportportal/agent-java-junit/releases/tag/5.0.0-BETA-16)
