### ISSUE TITLE
agent-java-junit:5.0.0-BETA-8

### ISSUE THREAD

**Issue by jbadeau** [reportportal/agent-java-junit#65]
jar agent-java-junit:5.0.0-BETA-8 

references

jar client-java:8934ff9

I dont see this version anywhere in your repo: http://dl.bintray.com/epam/reportportal/com/epam/reportportal/client-java/

Any idea? Where does the version: 8934ff9 come from?

**Comment by HardNorth** [comment]
A build issue. I'll try to fix in the next release.

**Comment by jbadeau** [comment]
thanx. Any eta?

**Comment by jbadeau** [comment]
??? is version 5 supposed to be used with RP5?

**Comment by HardNorth** [comment]
@jbadeau yes

**Comment by jbadeau** [comment]
Will there there be a release soon?

**Comment by HardNorth** [comment]
The most certain estimation I can give "Somewhere in a few weeks".

**Comment by HardNorth** [comment]
Well, I think I didn't get your question first time. You can freely use V4 agent with RP 5. V5 agent only contains fixes and new functionality.

BTW I've released 5.0.0-BETA-9 agent recently. So I believe it's closed. Feel free to re-open if you have any additional questions.
